### ISSUE TITLE
Explicit TODO Collection

### ISSUE THREAD

**Issue by BryceStevenWilley** [MassLegalHelp/docassemble-HelpForChildSupportObligors#20]
Because they're easier to track here:

* [ ] [Should we send people to MassLegalHelp Changing a child support order?](https://github.com/BryceStevenWilley/docassemble-DeadBrokeDads2/blob/63bfc1c877feed3db4a6dddec888de24b90a7180/docassemble/DeadBrokeDads2/data/questions/dbd-02-compare.yml#L191)
* [x] [How can our users actually answer this question? And what if the answer is no?](https://github.com/BryceStevenWilley/docassemble-DeadBrokeDads2/blob/63bfc1c877feed3db4a6dddec888de24b90a7180/docassemble/DeadBrokeDads2/data/questions/dbd-04-reasons-for-problem.yml#L195)
  * also in [reasons-for-review](https://github.com/BryceStevenWilley/docassemble-DeadBrokeDads2/blob/63bfc1c877feed3db4a6dddec888de24b90a7180/docassemble/DeadBrokeDads2/data/questions/dbd-04-reasons-for-review.yml#L271) and [reasons-for-problem-archive](https://github.com/BryceStevenWilley/docassemble-DeadBrokeDads2/blob/63bfc1c877feed3db4a6dddec888de24b90a7180/docassemble/DeadBrokeDads2/data/questions/dbd-04-reasons-for-problem-archive.yml#L195), is the answer in the reasons-for-review file?
* [ ] [if our user is incarcerated right now would they be able to do this? Or would someone else possibly be taking this interview for them and then getting them to sign?](https://github.com/BryceStevenWilley/docassemble-DeadBrokeDads2/blob/63bfc1c877feed3db4a6dddec888de24b90a7180/docassemble/DeadBrokeDads2/data/questions/dbd-05-other-considerations.yml#L277)
* [ ] [if user checks more than one of the above, (for correctional facilities) - which name do we want them to give?](https://github.com/BryceStevenWilley/docassemble-DeadBrokeDads2/blob/63bfc1c877feed3db4a6dddec888de24b90a7180/docassemble/DeadBrokeDads2/data/questions/dbd-05-other-considerations.yml#L278)
